source "https://rubygems.org"
gemspec

gem 'jekyll-admin', group: :jekyll_plugins
gem 'jekyll-sitemap'

gem 'csv'
gem 'faraday-retry'
gem 'webrick'
gem 'sass-embedded', '~> 1.62'
gem 'sass-rails', '~> 5.0'
gem 'sassc-rails', '~> 2.1.0'