name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop # 배포를 트리거할 브랜치를 설정 (main과 develop에서 자동 배포).

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and Sync
        run: chmod +x ./build.sh && sh ./build.sh

      - name: Push to personal repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: "output"
          destination-github-username: s-ja
          destination-repository-name: linkle_deploy
          target-branch: main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FOR_DEPLOY }} # 저장된 토큰 참조
          user-email: ${{ secrets.EMAIL }} # 이메일 정보 참조
