name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 모든 브랜치와 태그의 전체 히스토리 가져오기

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1" # 필요한 Node.js 버전을 지정.

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: creates output directory
        run: sh ./build.sh

      - name: Check if there are changes to commit
        run: |
          if ! git diff --quiet; then
            echo "Changes detected"
          else
            echo "No changes to commit"
            exit 0
          fi

      - name: Push to personal repository
        if: success() && steps.checkout.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: s-ja/linkle
          branch: main
          directory: output
          github_token: ${{ secrets.FOR_DEPLOY }}
          force: true

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
